
$background = rgba(13140dff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(303129ff)

$inverse_primary = rgba(566422ff)

$inverse_surface = rgba(e4e3d7ff)

$on_background = rgba(e4e3d7ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(2a3400ff)

$on_primary_container = rgba(d9eb99ff)

$on_primary_fixed = rgba(171e00ff)

$on_primary_fixed_variant = rgba(3f4c0bff)

$on_secondary = rgba(2e331bff)

$on_secondary_container = rgba(e0e6c3ff)

$on_secondary_fixed = rgba(191d08ff)

$on_secondary_fixed_variant = rgba(444930ff)

$on_surface = rgba(e4e3d7ff)

$on_surface_variant = rgba(c7c8b8ff)

$on_tertiary = rgba(033730ff)

$on_tertiary_container = rgba(bdece1ff)

$on_tertiary_fixed = rgba(00201bff)

$on_tertiary_fixed_variant = rgba(214e46ff)

$outline = rgba(919283ff)

$outline_variant = rgba(46483cff)

$primary = rgba(bdce80ff)

$primary_container = rgba(3f4c0bff)

$primary_fixed = rgba(d9eb99ff)

$primary_fixed_dim = rgba(bdce80ff)

$scrim = rgba(000000ff)

$secondary = rgba(c4caa9ff)

$secondary_container = rgba(444930ff)

$secondary_fixed = rgba(e0e6c3ff)

$secondary_fixed_dim = rgba(c4caa9ff)

$shadow = rgba(000000ff)

$source_color = rgba(56651eff)

$surface = rgba(13140dff)

$surface_bright = rgba(393a31ff)

$surface_container = rgba(1f2019ff)

$surface_container_high = rgba(292b23ff)

$surface_container_highest = rgba(34352dff)

$surface_container_low = rgba(1b1c15ff)

$surface_container_lowest = rgba(0d0f08ff)

$surface_dim = rgba(13140dff)

$surface_tint = rgba(bdce80ff)

$surface_variant = rgba(46483cff)

$tertiary = rgba(a1d0c5ff)

$tertiary_container = rgba(214e46ff)

$tertiary_fixed = rgba(bdece1ff)

$tertiary_fixed_dim = rgba(a1d0c5ff)


