
$background = rgba(171216ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(352e33ff)

$inverse_primary = rgba(804d79ff)

$inverse_surface = rgba(ecdfe5ff)

$on_background = rgba(ecdfe5ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(4c1f48ff)

$on_primary_container = rgba(ffd7f4ff)

$on_primary_fixed = rgba(340831ff)

$on_primary_fixed_variant = rgba(663560ff)

$on_secondary = rgba(3d2b39ff)

$on_secondary_container = rgba(f8daeeff)

$on_secondary_fixed = rgba(271624ff)

$on_secondary_fixed_variant = rgba(554150ff)

$on_surface = rgba(ecdfe5ff)

$on_surface_variant = rgba(d1c2cbff)

$on_tertiary = rgba(4c261aff)

$on_tertiary_container = rgba(ffdbd0ff)

$on_tertiary_fixed = rgba(321207ff)

$on_tertiary_fixed_variant = rgba(663c2eff)

$outline = rgba(9a8d95ff)

$outline_variant = rgba(4e444bff)

$primary = rgba(f2b3e5ff)

$primary_container = rgba(663560ff)

$primary_fixed = rgba(ffd7f4ff)

$primary_fixed_dim = rgba(f2b3e5ff)

$scrim = rgba(000000ff)

$secondary = rgba(dabfd2ff)

$secondary_container = rgba(554150ff)

$secondary_fixed = rgba(f8daeeff)

$secondary_fixed_dim = rgba(dabfd2ff)

$shadow = rgba(000000ff)

$source_color = rgba(453341ff)

$surface = rgba(171216ff)

$surface_bright = rgba(3e373cff)

$surface_container = rgba(241e22ff)

$surface_container_high = rgba(2f282dff)

$surface_container_highest = rgba(3a3337ff)

$surface_container_low = rgba(201a1eff)

$surface_container_lowest = rgba(120d11ff)

$surface_dim = rgba(171216ff)

$surface_tint = rgba(f2b3e5ff)

$surface_variant = rgba(4e444bff)

$tertiary = rgba(f5b8a6ff)

$tertiary_container = rgba(663c2eff)

$tertiary_fixed = rgba(ffdbd0ff)

$tertiary_fixed_dim = rgba(f5b8a6ff)


